# Build instructions for https://antora.org/, "The multi-repository documentation site generator for tech writers who writing in AsciiDoc"
# BEWARE: Keep `antora-playbook-local.yml` in sync with this one
site:
  title: Fulcro Community
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://fulcro-community.github.io/
  start_page: main::index.adoc
content:
  sources:
  - url: . # 'main' module
  # Note: embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: https://github.com/fulcro-community/guides.git # 'guides' module
  #- url: /fulcro-community/guides # 'guides' module
ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/fulcro-community/antora-ui-default/releases/download/v3/ui-bundle.zip
    snapshot: true
  # Instruct Antora to create .nojekyll file so GH Pages will not screw up our content
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
