# Build instructions for https://antora.org/, "The multi-repository documentation site generator for tech writers who writing in AsciiDoc"
site:
  title: Fulcro Community
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://fulcro-community.github.io/
  start_page: main::index.adoc
content:
  sources:
  - url: https://github.com/fulcro-community/fulcro-community.github.io.git # 'main' module
  #- url: /antora # 'main' module as seen from within the antora docker image, see ./build-locally.sh
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  #- url: https://github.com/fulcro-community/guides.git
 # url: /fulcro-community/guides
 # branches: [main]
 # start_path: guides
  # - url: https://github.com/fulcro-community/awesome-fulcro.git
  #   start_path: awesome-fulcro
ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/fulcro-community/antora-ui-default/releases/download/v1/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
